# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a21a8ac6f307a3acac45147253e659471487b0f46c5eee4294c204272994b7c7ddbdf3e5ff7d5d1a2b2215dbe4b7e035a9c0293aa584b47bfc1f307fa4d9fcf

test:
  secret_key_base: fcd770255eb82d1cb6fee082098b0ba1d4cc54798381c9e299777e5bc5789fc78debb331f4839cce1fd9fad2dff6c5f91190e98679f503ec8a85234530514849

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
